DISPENSER/pharm/pharmacy/urls.py
from django.urls import path
from .import HODViews
from .import pharmacistViews,DoctorViews,views,patient_view,clerkViews
from django.contrib.auth import views as auth_views


urlpatterns=[
    path('',HODViews.adminDashboard,name='admin_dashboard'),
    path('admin_user/patient_form/',HODViews.createPatient,name='patient_form'),
    path('admin_user/all_patients/',HODViews.allPatients,name='all_patients'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutUser,name='logout'), 
    # path('get_user_details/', views.get_user_details, name="get_user_details"),

    path('admin_user/add_pharmacist/',HODViews.createPharmacist,name='add_pharmacist'),
    path('admin_user/manage_pharmacist/',HODViews.managePharmacist,name='manage_pharmacist'),
    path('admin_user/add_doctor/',HODViews.createDoctor,name='add_doctor'),
    path('admin_user/manage_doctor/',HODViews.manageDoctor,name='manage_doctor'),
    path('admin_user/add_pharmacyClerk/',HODViews.createPharmacyClerk,name='add_pharmacyClerk'),
    path('admin_user/admin_user/manage_pharmacyClerk/',HODViews.managePharmacyClerk,name='manage_pharmacyClerk'),
    path('admin_user/add_stock/',HODViews.addStock,name='add_stock'),
    path('admin_user/add_category/',HODViews.addCategory,name='add_category'),
    path('admin_user/manage_stock/',HODViews.manageStock,name='manage_stock'),    
    path('admin_user/prescribe_drug/',HODViews.addPrescription,name='prescribe'),
    path('admin_user/edit_patient/<patient_id>/',HODViews.editPatient,name='edit_patient'),
    # path('add_patient_save/',HODViews.editPatientSave,name='edit_patient_save'),

    path('admin_user/delete_patient/<str:pk>/',HODViews.confirmDelete,name='delete_patient'),
    path('admin_user/patient_personalRecords/<pk>/',HODViews.patient_personalRecords,name='patient_record'),
    path('admin_user/delete_prescription/<str:pk>/',HODViews.deletePrescription,name='delete_prescription'),
    path('admin_user/doctor_profile/',DoctorViews.doctorProfile,name='doctor_profile'),
    path('admin_user/hod_profile/',HODViews.hodProfile,name='hod_profile'),
    path('admin_user/delete_doctor/<str:pk>/',HODViews.deleteDoctor,name='delete_doctor'),
    path('admin_user/delete_pharmacist/<str:pk>/',HODViews.deletePharmacist,name='delete_pharmacist'),
    path('admin_user/delete_receptionist/<str:pk>/',HODViews.deletePharmacyClerk,name='delete_clerk'),
    path('admin_user/hod_profile/editAdmin_profile/',HODViews.editAdmin,name='edit-admin'),
    path('admin_user/delete_drug/<str:pk>/',HODViews.deleteDrug,name='delete_drug'),


    path('admin_user/edit_pharmacist/<staff_id>/', HODViews.editPharmacist, name="edit_pharmacist"),
    path('admin_user/edit_doctor/<doctor_id>/', HODViews.editDoctor, name="edit_doctor"),
    path('admin_user/edit_receptionist/<clerk_id>/', HODViews.editPharmacyClerk, name="edit_clerk"),
    path('admin_user/edit_drug/<pk>/', HODViews.editStock, name="edit_drug"),
    path('admin_user/receive_drug/<pk>/', HODViews.receiveDrug, name="receive_drug"),
    path('admin_user/reorder_level/<str:pk>/', HODViews.reorder_level, name="reorder_level"),
    path('admin_user/drug_details/<str:pk>/', HODViews.drugDetails, name="drug_detail"),
    path('patient_feedback_message/', pharmacistViews.patient_feedback_message, name="patient_feedback_message"),
    path('patient_feedback_message_reply/', pharmacistViews.patient_feedback_message_reply, name="patient_feedback_message_reply"),
    path('admin_user/delete_patient_feedback/<str:pk>/', pharmacistViews.deletefeedback, name="delete_fed"),

        path('delete_details/<str:pk>/', pharmacistViews.deleteDispense4, name="del_disp"),



    #Pharmacist
    path('pharmacist_home/',pharmacistViews.pharmacistHome,name='pharmacist_home'),
    path('pharmacist_manage_patients/',pharmacistViews.managePatientsPharmacist,name='manage_patient_pharmacist'),
    path('manage_disp/<pk>/',pharmacistViews.manageDispense,name='pharmacist_disp'),
#    path('manage_dispe/<str:pk>/',pharmacistViews.dispenseDrug,name='pharm_disp'),
    # path('manage_stock_form/<str:pk>/',pharmacistViews.dispense,name='pharm_disp2'),
    path('staff_profile/',pharmacistViews.userProfile,name='pharmacist_profile'),

    path('manage_stock2/',pharmacistViews.manageStock,name='manage_stock2'),    
    path('manage_prescrip/',pharmacistViews.managePrescription,name='pharmacist_prescription'),
    path('pharmacist_user/drug_details/<str:pk>/', pharmacistViews.drugDetails, name="drug_detail2"),



    #Doctor
    path('doctor_home/',DoctorViews.doctorHome,name='doctor_home'),
    path('manage_patients/',DoctorViews.managePatients,name='manage_patient_doctor'),
    path('doctor_prescribe_drug/<str:pk>/',DoctorViews.addPrescription,name='doctor_prescribe2'),
    path('patient_personalDetails/<str:pk>/',DoctorViews.patient_personalDetails,name='patient_record_doctor'),
    path('manage_prescription_doctor/',DoctorViews.managePrescription,name='manage_precrip_doctor'),
    path('doctor_prescribe_delete/<str:pk>/',DoctorViews.deletePrescription,name='doctor_prescrip_delete'),
    path('doctor_prescribe_edit/<str:pk>/',DoctorViews.editPrescription,name='doctor_prescrip_edit'),

    #Patients
    path('patient_profile/',patient_view.patientProfile,name='patient_profile'),
    path('patient_home/',patient_view.patientHome,name='patient_home'),
    path('patient_feedback/',patient_view.patient_feedback,name='patient_feedback'),
    path('staff_feedback_save/', patient_view.patient_feedback_save, name="patient_feedback_save"),
    path('taken_home/',patient_view.patient_dispense3,name='taken_home'),
    path('delete_patient_feedback2/<str:pk>/',patient_view.Patientdeletefeedback, name="delete_fed2"),
    path('delete_dispen/',patient_view.myPrescriptionDelete,name='taken_delete'),

    #Receptionist
    path('receptionist_profile/',clerkViews.receptionistProfile,name='clerk_profile'),
    path('receptionist_home/',clerkViews.clerkHome,name='clerk_home'),
    path('receptionist/patient_form/',clerkViews.createPatient,name='patient_form2'),
    path('receptionist/all_patients/',clerkViews.allPatients,name='all_patients2'),
    path('receptionist/edit_patient/<patient_id>/',clerkViews.editPatient,name='edit_patient_clerk'),
    path('receptionist/patient_personalRecords/<str:pk>/',clerkViews.patient_personalRecords,name='patient_record_clerk'),
    path('receptionist/delete_patient/<str:pk>/',clerkViews.confirmDelete,name='delete_patient_clerk'),
    # path('receptionist/dispense_drug/<str:pk>/',pharmacistViews.dispenseDrug,name='dispense_drug'),


  
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="reset_password"),

    path('reset_password_sent/',auth_views.PasswordResetDoneView
    .as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView
    .as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),



    

   path('reset_password_complete/',auth_views.PasswordResetCompleteView
    .as_view(template_name="password_reset_done.html"),name="password_reset_complete"),
]

DISPENSER/pharm/pharmacy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber

from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.core.cache import cache 
from django.db.models import BooleanField, ExpressionWrapper, Q
from django.db.models.functions import Now


class CustomUser(AbstractUser):
    user_type_data = ((1, "AdminHOD"), (2, "Pharmacist"), (3, "Doctor"), (4, "PharmacyClerk"),(5, "Patients"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)

class Patients(models.Model):
    gender_category=(
        ('Male','Male'),
        ('Female','Female'),
    )
    admin = models.OneToOneField(CustomUser,null=True, on_delete = models.CASCADE)
    reg_no=models.CharField(max_length=30,null=True,blank=True,unique=True)
    gender=models.CharField(max_length=7,null=True,blank=True,choices=gender_category)
    first_name=models.CharField(max_length=20,null=True,blank=True)
    last_name=models.CharField(max_length=20,null=True,blank=True)
    dob=models.DateTimeField(auto_now_add= False, auto_now=False,null=True,blank=True)
    phone_number=models.CharField(max_length=10,null=True,blank=True)
    profile_pic=models.ImageField(default="patient.jpg",null=True,blank=True)
    age= models.IntegerField(default='0', blank=True, null=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    date_admitted=models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.admin)



class AdminHOD(models.Model):
    gender_category=(
        ('Male','Male'),
        ('Female','Female'),
    )
    admin = models.OneToOneField(CustomUser,null=True, on_delete = models.CASCADE)
    emp_no= models.CharField(max_length=100,null=True,blank=True)
    gender=models.CharField(max_length=100,null=True,choices=gender_category)
    mobile=models.CharField(max_length=10,null=True,blank=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    profile_pic=models.ImageField(default="admin.png",null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    date_employed=models.DateTimeField(auto_now_add=True, auto_now=False)
    objects = models.Manager()
    def __str__(self):
        return str(self.admin)
    


class Pharmacist(models.Model):
    gender_category=(
        ('Male','Male'),
        ('Female','Female'),
    )
    admin = models.OneToOneField(CustomUser,null=True, on_delete = models.CASCADE)
    emp_no=models.CharField(max_length=100,null=True,blank=True)
    age= models.IntegerField(default='0', blank=True, null=True)
    gender=models.CharField(max_length=100,null=True,choices=gender_category)
    mobile =models.CharField(max_length=10,null=True,blank=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    profile_pic=models.ImageField(default="images2.png",null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    def __str__(self):
        return str(self.admin)

    
class Doctor(models.Model):
    gender_category=(
        ('Male','Male'),
        ('Female','Female'),
    )
    admin = models.OneToOneField(CustomUser,null=True, on_delete = models.CASCADE)
    emp_no=models.CharField(max_length=100,null=True,blank=True)
    age= models.IntegerField(default='0', blank=True, null=True)
    gender=models.CharField(max_length=100,null=True,choices=gender_category)
    mobile=models.CharField(max_length=10,null=True,blank=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    profile_pic=models.ImageField(default="doctor.png",null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    def __str__(self):
        return str(self.admin)
	

class PharmacyClerk(models.Model):
    gender_category=(
        ('Male','Male'),
        ('Female','Female'),
    )
    admin = models.OneToOneField(CustomUser,null=True, on_delete = models.CASCADE)
    emp_no=models.CharField(max_length=100,null=True,blank=True)
    gender=models.CharField(max_length=100,null=True,choices=gender_category)
    mobile=models.CharField(max_length=10,null=True,blank=True)
    address=models.CharField(max_length=300,null=True,blank=True)
    profile_pic=models.ImageField(default="images2.png",null=True,blank=True)
    age= models.IntegerField(default='0', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    def __str__(self):
        return str(self.admin)
	
    

class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=True)
    
    def __str__(self):
        return str(self.name)
	

    
class Prescription(models.Model):
    patient_id = models.ForeignKey(Patients,null=True, on_delete=models.SET_NULL)
    description=models.TextField(null=True)
    prescribe=models.CharField(max_length=100,null=True)
    date_precribed=models.DateTimeField(auto_now_add=True, auto_now=False)




class ExpiredManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().annotate(
            expired=ExpressionWrapper(Q(valid_to__lt=Now()), output_field=BooleanField())
        )

class Stock(models.Model):
    category = models.ForeignKey(Category,null=True,on_delete=models.CASCADE,blank=True)
    drug_imprint=models.CharField(max_length=6 ,blank=True, null=True)
    drug_name = models.CharField(max_length=50, blank=True, null=True)
    drug_color = models.CharField(max_length=50, blank=True, null=True)
    drug_shape = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_quantity = models.IntegerField(default='0', blank=True, null=True)
    reorder_level = models.IntegerField(default='0', blank=True, null=True)
    manufacture= models.CharField(max_length=50, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    drug_strength= models.CharField(max_length=10, blank=True, null=True)
    valid_from = models.DateTimeField(blank=True, null=True,default=timezone.now)
    valid_to = models.DateTimeField(blank=False, null=True)
    drug_description=models.TextField(blank=True,max_length=1000,null=True)
    drug_pic=models.ImageField(default="images2.png",null=True,blank=True)
    objects = ExpiredManager()
   
    def __str__(self):
        return str(self.drug_name)
   
    
class Dispense(models.Model):
    
    patient_id = models.ForeignKey(Patients, on_delete=models.DO_NOTHING,null=True)
    drug_id = models.ForeignKey(Stock, on_delete=models.SET_NULL,null=True,blank=False)
    dispense_quantity = models.PositiveIntegerField(default='1', blank=False, null=True)
    taken=models.CharField(max_length=300,null=True, blank=True)
    stock_ref_no=models.CharField(max_length=300,null=True, blank=True)
    instructions=models.TextField(max_length=300,null=True, blank=False)
    dispense_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)


class PatientFeedback(models.Model):
    id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey(Patients, on_delete=models.CASCADE)
    admin_id= models.ForeignKey( AdminHOD,null=True, on_delete=models.CASCADE)
    pharmacist_id=models.ForeignKey( Pharmacist,null=True, on_delete=models.CASCADE)
    feedback = models.TextField(null=True)
    feedback_reply = models.TextField(null=True)
    admin_created_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()





@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type == 2:
            Pharmacist.objects.create(admin=instance,address="")
        if instance.user_type == 3:
            Doctor.objects.create(admin=instance,address="")
        if instance.user_type == 4:
            PharmacyClerk.objects.create(admin=instance,address="")
        if instance.user_type == 5:
            Patients.objects.create(admin=instance,address="")
       
       
       

@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminhod.save()
    if instance.user_type == 2:
        instance.pharmacist.save()
    if instance.user_type == 3:
        instance.doctor.save()
    if instance.user_type == 4:
        instance.pharmacyclerk.save()
    if instance.user_type == 5:
        instance.patients.save()


   



 

DISPENSER/pharm/pharmacy/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
 
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">

 
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link href="{% static 'jquery-ui2/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.theme.min.css' %}" rel="stylesheet">



</head>
<body>
{% block main_content %}
{% endblock %}
   

<script>
  setTimeout(function() {
$('.alert').fadeOut();
}, 1200); 
</script>
  




</script>
<script src="{% static "jquery/jquery.min.js"  %}"></script>

<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>

<script src="{% static 'jquery-ui2/jquery-ui.min.js' %}"></script>
<script src="{% static 'jquery-ui2/jquery-ui.js' %}"></script>
<script src="{% static 'js/datejs.js' %}"></script>


</body>
</html>

DISPENSER/pharm/pharmacy/templates/base_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pharmacy Dispensing System</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="{% static 'css/profile.css'%}">

    <link rel="stylesheet" href="{% static " fontawesome-free/css/all.min.css " %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">


    <link rel="stylesheet" href="{% static 'dist/css/adminlte.css'  %}">
    <link rel="stylesheet" href="{% static 'pace-progress/themes/black/pace-theme-flat-top.css' %}">
    <link rel="stylesheet" href="{% static 'datatables-bs4/css/dataTables.bootstrap4.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables-responsive/css/responsive.bootstrap4.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables-buttons/css/buttons.bootstrap4.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link href="{% static 'jquery-ui2/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'jquery-ui2/jquery-ui.structure.min.css' %}" rel="stylesheet">
    <link href="{% static 'jquery-ui2/jquery-ui.theme.min.css' %}" rel="stylesheet">


</head>
{% block htm %} {% endblock htm%}



<script src="{% static " jquery/jquery.min.js "  %}"></script>

<!-- Bootstrap 4 -->
<script src="{% static " bootstrap/js/bootstrap.bundle.min.js "  %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>

<script src="{% static 'jquery-ui2/jquery-ui.min.js' %}"></script>
<script src="{% static 'jquery-ui2/jquery-ui.js' %}"></script>
<!-- jquery slimscroll js -->
<script src="{% static 'jquery-slimscroll/js/jquery.slimscroll.js'%}"></script>
<!-- modernizr js -->
<!-- classie js -->
<!-- i18next.min.js -->
<script src="{% static 'i18next/js/i18next.min.js'%}"></script>
<script src="{% static 'i18next-xhr-backend/js/i18nextXHRBackend.min.js'%}"></script>

<script src="{% static 'js/paging.js' %}"></script>


<script src="{% static 'pace-progress/pace.min.js' %}"></script>

<script src="{% static 'datatables/jquery.dataTables.js'%}"></script>
<script src="{% static 'datatables-bs4/js/dataTables.bootstrap4.min.js'%} "></script>
<script src="{% static 'datatables-responsive/js/dataTables.responsive.min.js'%} "></script>
<script src="{% static 'datatables-responsive/js/responsive.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.bootstrap4.min.js'%}"></script>
<script src="{% static 'pdfmake/pdfmake.min.js'%}"></script>
<script src="{% static 'pdfmake/vfs_fonts.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.html5.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.print.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.colVis.min.js'%}"></script>
<script src="{% static 'js/select2.min.js'%}"></script>

<script src="{% static 'js/datejs.js' %}"></script>

{% block js%} {% endblock %}
<script>
    $(document).ready(function() {
        $(function() {

            $("#plist").DataTable({
                "responsive": true,
                "lengthChange": true,
                "autoWidth": false,
                "buttons": ["excel", "print"],
                "lengthMenu": [5]
            }).buttons().container().appendTo('#plist_wrapper .col-md-6:eq(0)');
            // $('#plist').DataTable({
            //   "lengthChange": true,

            //   "lengthMenu":[5]
            // });

        });
    });
</script>

<script>
    $("#id_drug_id").select2({
        placeholder: "Dispense Drug Here",
        allowClear: true
    });
    $("#id_drug_id").select2();
    $("#id_drug_id").on("select2:open", function(e) {

        $('#id_drug_id').change(function() {
            var data = $(this).val();
            // alert(data);       
            $("#id_taken").val(data)

        });

        $('#select2-search__field')
            .text(drugname)
            .trigger('change');
    });
    $('#id_drug_id').select2({
        placeholder: " Search Dispense Drug here",
        width: "100%",
        height: "45px"



    });
</script>
</body>

</html>

DISPENSER/pharm/pharmacy/templates/password_reset.html
{% extends 'base.html'%} {% load crispy_forms_tags %} {% block main_content %} {% load static %}
<style>
    .reset {
        height: 100vh;
    }
    
    .fa-lock {
        font-size: 4rem;
        color: rgb(196, 238, 255);
    }
    
    .btn {
        background: #64d3ff !important;
        transition: all .5s;
    }
    
    .btn:hover {
        background: rgb(90, 169, 243) !important;
        color: black !important;
    }
    
    .card {
        border-radius: 10px;
    }
    
    .form-group {
        margin-top: 30px !important;
    }
</style>
<div class="reset bg-light">
    <div class="container h-100">
        <div class="row  d-flex justify-content-center align-content-center h-100">
            <div class="col-md-5">
                <div class="card py-5 ">
                    <div class="card-body">
                        <div class="d-flex justify-content-center">
                            <i class="fas fa-lock text-center "></i>

                        </div>
                        <h3 class="text-center pt-3">Password reset</h3>


                        <div class="card-body">
                            <p class="text-center">Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
                            <form method="post">

                                {% csrf_token %} {{form|crispy}}
                                <input type="Submit" class="btn  btn-block btn-primary mt-5" name="Send email">

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</div>

<div>



</div>


{% endblock main_content %}